version: "3.8"
services:
  user_service:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    depends_on:
      - user_mongodb
  user_mongodb:
    image: mongo:latest
    container_name: user_mongodb
    ports:
      - "27018:27018"